### ISSUE TITLE
Add better address validation

### ISSUE THREAD

**Issue by tonyklapatch** [poconosewandvac/Commerce_AddressManager#3]
Currently only checks if field is empty. Add support for built in Basic Address Validation and Country Validation as well as custom validators.

**Comment by Mark-H** [comment]
You can probably trigger the validate address event to support the exact same validation as the core address handling.

**Comment by tonyklapatch** [comment]
That's what I'm planning on using, especially since the lob address verification module uses it.

**Comment by tonyklapatch** [comment]
This is fixed in 2.0 (coming soon).
